  server:
    port: 8761
    address: localhost
  spring:
    security:
      user:
        name: root
        password: root
  security:
    basic:
      enabled: false
  eureka:
    instance:
      hostname: localhost
    client:
      fetch-registry: false
      register-with-eureka: false
      serviceUrl:
        defaultZone: http://root:root@localhost:8761/eureka